[versions]
kotlin = "2.3.10"
ktor = "3.4.0"
reactWrappers = "2026.2.16-19.2.4"
junit = "6.0.3"
detekt = "1.22.0"
ktlint = "14.0.1"
serialization = "1.10.0"
logback = "1.5.32"

[libraries]
ktor-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-contentNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-requestValidation = { module = "io.ktor:ktor-server-request-validation", version.ref = "ktor" }
ktor-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-swagger = { module = "io.ktor:ktor-server-swagger-jvm", version.ref = "ktor" }
ktor-openapi = { module = "io.ktor:ktor-server-openapi-jvm", version.ref = "ktor" }
ktor-statusPages = { module = "io.ktor:ktor-server-status-pages-jvm", version.ref = "ktor" }
ktor-host = { module = "io.ktor:ktor-server-host-common-jvm", version.ref = "ktor" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

mongodb-coroutine-driver = { module = "org.mongodb:mongodb-driver-kotlin-coroutine", version = "5.6.3" }
mongodb-bson-kotlinx = { module = "org.mongodb:bson-kotlinx", version = "5.6.3" }

react = { module = "org.jetbrains.kotlin-wrappers:kotlin-react", version.ref = "reactWrappers" }
react-dom = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-dom", version.ref = "reactWrappers" }
emotion = { module = "org.jetbrains.kotlin-wrappers:kotlin-emotion", version = "2025.3.26" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

[bundles]
ktor = ["ktor-core", "ktor-netty", "ktor-json", "ktor-contentNegotiation", "ktor-requestValidation", "ktor-cors", "ktor-swagger", "ktor-openapi", "ktor-statusPages", "ktor-host"]
test = ["junit-api", "junit-engine"]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }